# Generated by Django 5.2.6 on 2025-09-09 15:31

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', encrypted_model_fields.fields.EncryptedDateField()),
                ('category', encrypted_model_fields.fields.EncryptedCharField()),
                ('description', encrypted_model_fields.fields.EncryptedTextField()),
                ('amount', encrypted_model_fields.fields.EncryptedCharField()),
                ('type', models.CharField(default='expense', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='core_transa_user_id_c94326_idx'), models.Index(fields=['date'], name='core_transa_date_2d33ba_idx')],
            },
        ),
    ]
